# Generated by Django 5.0.6 on 2024-05-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente2',
            name='password',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
    ]
