# Generated by Django 5.0.6 on 2024-05-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utente', '0002_utente2_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente2',
        ),
    ]
