# Generated by Django 5.0.6 on 2024-05-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_utente', '0003_delete_utente2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utente',
            options={'verbose_name': 'Utente', 'verbose_name_plural': 'Utenti'},
        ),
    ]
