# Generated by Django 5.0.6 on 2024-05-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='citta',
            field=models.CharField(default='Reggio Emilia', max_length=100, verbose_name='citta'),
            preserve_default=False,
        ),
    ]
