# Generated by Django 5.0.6 on 2024-05-27 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='data_pubblicazione',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='data di pubblicazione'),
            preserve_default=False,
        ),
    ]
