# Generated by Django 5.0.6 on 2024-05-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='tag'),
        ),
    ]
