# Generated by Django 5.0.6 on 2024-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0002_alter_utente_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='annunciolavoro',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is_available'),
        ),
    ]
