# Generated by Django 5.0.6 on 2024-05-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0002_recensione_data_pubblicazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, default='photot/default.jpg', null=True, upload_to='photo/'),
        ),
    ]
