# Generated by Django 5.0.6 on 2024-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0004_lavoro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lavoro',
            name='status',
            field=models.CharField(default='pending', max_length=200, verbose_name='status'),
        ),
    ]
