# Generated by Django 5.0.6 on 2024-05-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0004_alter_utente_immagine_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
