# Generated by Django 5.0.6 on 2024-05-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0005_lavoro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoro',
            name='status',
            field=models.CharField(choices=[('In attesa', 'In attesa'), ('Accettato', 'Accettato'), ('Rifiutato', 'Rifiutato')], default='In attesa', max_length=200, verbose_name='status'),
        ),
    ]
