# Generated by Django 5.0.6 on 2024-05-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0006_alter_lavoro_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lavoro',
            name='status',
        ),
        migrations.AddField(
            model_name='lavoro',
            name='stato',
            field=models.CharField(choices=[('In attesa', 'In attesa'), ('Accettato', 'Accettato'), ('Rifiutato', 'Rifiutato')], default='In attesa', max_length=200, verbose_name='stato'),
        ),
    ]
