# Generated by Django 5.0.6 on 2024-05-31 12:15

import utente.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0006_alter_utente_immagine_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavoro',
            name='stato',
            field=models.CharField(choices=[('In attesa', 'In attesa'), ('Accettato', 'Accettato'), ('Rifiutato', 'Rifiutato'), ('Terminato', 'Terminato')], default='In attesa', max_length=200, verbose_name='stato'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='immagine_profilo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to=utente.models.upload_to),
        ),
    ]
