# Generated by Django 5.0.6 on 2024-05-27 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0007_remove_lavoro_status_lavoro_stato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valutazione', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='valutazione')),
                ('commento', models.TextField(verbose_name='commento')),
                ('azienda', models.ForeignKey(limit_choices_to={'is_azienda': True}, on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_azienda', to=settings.AUTH_USER_MODEL)),
                ('lavoratore', models.ForeignKey(limit_choices_to={'is_azienda': False}, on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_lavoratore', to=settings.AUTH_USER_MODEL)),
                ('lavoro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni', to='utente.lavoro')),
            ],
            options={
                'verbose_name': 'Recensione',
                'verbose_name_plural': 'Recensioni',
            },
        ),
    ]
