<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-06-01 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0007_alter_lavoro_stato_alter_utente_immagine_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensione_destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='mittente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensione_mittente', to=settings.AUTH_USER_MODEL),
        ),
    ]
=======
# Generated by Django 5.0.6 on 2024-06-01 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0007_alter_lavoro_stato_alter_utente_immagine_profilo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensione_destinatario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='mittente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensione_mittente', to=settings.AUTH_USER_MODEL),
        ),
    ]
>>>>>>> 6922e3ef929380bfbd6f2c6b085c610217e22633
