# Generated by Django 5.0.6 on 2024-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0008_recensione'),
    ]

    operations = [
        migrations.AddField(
            model_name='recensione',
            name='titolo',
            field=models.CharField(default='', max_length=200, verbose_name='titolo'),
            preserve_default=False,
        ),
    ]
