# Generated by Django 5.0.6 on 2024-06-01 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0008_alter_recensione_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annunciolavoro',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lavoro',
            name='annuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utente.annunciolavoro'),
        ),
        migrations.AlterField(
            model_name='lavoro',
            name='lavoratore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
