# Generated by Django 5.0.6 on 2024-06-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utente', '0009_alter_annunciolavoro_azienda_alter_lavoro_annuncio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recensione',
            name='lavoro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utente.lavoro'),
        ),
    ]
